# Module 3 Exercises - Data Manipulation

### Exercise 1:

From the datasets folder, load in the "dupedata.csv" file as a dataframe. Drop the duplicates from the dataframe, keeping the first value (save the resulting dataframe to a new variable).

In [1]:
#import libraries
import pandas as pd

In [2]:
location = "datasets/dupedata.csv"
dupedf=pd.read_csv(location)

In [15]:
dupe = dupedf.duplicated() #creates list of True/False values
dupedf[dupe] #shows rows where duplicated is True

,fname,lname,gender,age,exercise,hours,grade,address
1731,Henry,Stafford,male,14,3,11,75.7,"7071 Edgewater Rd., South Windsor, CT 06074"
1785,Aspen,Ayers,female,14,2,14,96.8,"8218 Yukon Ave., Hazleton, PA 18201"
1786,Signe,Bentley,female,14,1,6,71.8,"7008 Augusta Ave., Macomb, MI 48042"
1787,Lunea,Perkins,female,14,2,10,85.3,"956 Laurel Road, Oxford, MS 38655"
1788,Alvin,Bullock,male,16,1,18,90.1,"82 Thorne Ave., Ann Arbor, MI 48103"
1789,Herman,Potter,male,17,4,14,88.4,"833 Thompson Dr., Feasterville Trevose, PA 19053"
2006,Neil,Wooten,male,15,3,15,89.7,"400 Bridge Court, Soddy Daisy, TN 37379"
2007,Daquan,Alvarez,male,16,2,13,85.2,"9028 Arnold Circle, Elizabeth, NJ 07202"
2008,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013"
2009,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911"
2010,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801"
2011,Lareina,Poole,female,18,1,14,87.6,"59 Court Dr., Waxhaw, NC 28173"
2012,Medge,Mccarthy,female,15,1,8,75.8,"609 Warren Court, Prior Lake, MN 55372"
2013,Kibo,Gates,male,16,1,10,88.2,"24 Vernon Street, Helena, MT 59601"
2014,Libby,Guzman,female,19,1,19,100.0,"666 S. Pennington Rd., Dover, NH 03820"
2015,Shelly,Rosario,female,18,4,13,84.3,"571 Miles Street, Flowery Branch, GA 30542"
2016,Lane,Tate,male,19,4,11,84.2,"4 Old Westport St., Glen Burnie, MD 21060"
2017,Isadora,Case,female,18,3,11,79.1,"44 Ocean Lane, Appleton, WI 54911"
2018,Maggy,Whitfield,female,15,1,15,90.5,"2 Henry Ave., Palm Bay, FL 32907"
2019,Elton,Wagner,male,16,2,9,71.0,"98 Indian Spring St., Athens, GA 30605"
2020,Lance,Benjamin,male,14,5,18,90.3,"55 Creek Dr., Lorton, VA 22079"
2021,Kyle,Skinner,male,17,5,6,82.4,"8593 East Branch St., Mooresville, NC 28115"
2022,Colin,Cohen,male,14,1,10,83.8,"23 Lakewood Street, Lake Worth, FL 33460"
2023,Solomon,Mcpherson,male,15,5,18,94.5,"7465 North Pearl St., Massapequa Park, NY 11762"
2024,Marcia,Pugh,female,17,3,10,82.4,"9253 Richardson Road, Matawan, NJ 07747"
2025,Kadeem,Morrison,male,18,4,4,78.2,"33 Spring Dr., Taunton, MA 02780"
2026,Nash,Powell,male,18,5,9,79.3,"41 Hill Avenue, Mentor, OH 44060"
2027,Noelani,Wagner,female,14,2,7,83.2,"8839 Marshall St., Miami, FL 33125"
2028,Noelani,Cherry,female,18,4,15,87.4,"8304 Charles Rd., Lewis Center, OH 43035"
2029,Neil,Whitley,male,16,5,16,88.7,"40 Washington Ave., Bloomfield, NJ 07003"
2030,Nelle,Golden,female,17,1,9,80.2,"9768 Hanover Dr., Meadville, PA 16335"
2031,Armando,Hoffman,male,17,5,18,95.1,"360 Manor Drive, Northville, MI 48167"
2032,Illiana,Rojas,female,15,5,9,76.5,"9425 Studebaker Dr., Thibodaux, LA 70301"
2033,Neil,Wooten,male,15,3,15,89.7,"400 Bridge Court, Soddy Daisy, TN 37379"
2034,Daquan,Alvarez,male,16,2,13,85.2,"9028 Arnold Circle, Elizabeth, NJ 07202"
2035,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013"
2036,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911"
2037,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801"

In [7]:
#drops duplicate rows, default is to keep first observation
nodupedf = dupedf.drop_duplicates()
nodupedf

,fname,lname,gender,age,exercise,hours,grade,address
0,Marcia,Pugh,female,17,3,10,82.4,"9253 Richardson Road, Matawan, NJ 07747"
1,Kadeem,Morrison,male,18,4,4,78.2,"33 Spring Dr., Taunton, MA 02780"
2,Nash,Powell,male,18,5,9,79.3,"41 Hill Avenue, Mentor, OH 44060"
3,Noelani,Wagner,female,14,2,7,83.2,"8839 Marshall St., Miami, FL 33125"
4,Noelani,Cherry,female,18,4,15,87.4,"8304 Charles Rd., Lewis Center, OH 43035"
5,Neil,Whitley,male,16,5,16,88.7,"40 Washington Ave., Bloomfield, NJ 07003"
6,Nelle,Golden,female,17,1,9,80.2,"9768 Hanover Dr., Meadville, PA 16335"
7,Armando,Hoffman,male,17,5,18,95.1,"360 Manor Drive, Northville, MI 48167"
8,Illiana,Rojas,female,15,5,9,76.5,"9425 Studebaker Dr., Thibodaux, LA 70301"
9,Neil,Wooten,male,15,3,15,89.7,"400 Bridge Court, Soddy Daisy, TN 37379"
10,Daquan,Alvarez,male,16,2,13,85.2,"9028 Arnold Circle, Elizabeth, NJ 07202"
11,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013"
12,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911"
13,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801"
14,Lareina,Poole,female,18,1,14,87.6,"59 Court Dr., Waxhaw, NC 28173"
15,Medge,Mccarthy,female,15,1,8,75.8,"609 Warren Court, Prior Lake, MN 55372"
16,Kibo,Gates,male,16,1,10,88.2,"24 Vernon Street, Helena, MT 59601"
17,Libby,Guzman,female,19,1,19,100.0,"666 S. Pennington Rd., Dover, NH 03820"
18,Shelly,Rosario,female,18,4,13,84.3,"571 Miles Street, Flowery Branch, GA 30542"
19,Lane,Tate,male,19,4,11,84.2,"4 Old Westport St., Glen Burnie, MD 21060"
20,Isadora,Case,female,18,3,11,79.1,"44 Ocean Lane, Appleton, WI 54911"
21,Maggy,Whitfield,female,15,1,15,90.5,"2 Henry Ave., Palm Bay, FL 32907"
22,Elton,Wagner,male,16,2,9,71.0,"98 Indian Spring St., Athens, GA 30605"
23,Lance,Benjamin,male,14,5,18,90.3,"55 Creek Dr., Lorton, VA 22079"
24,Kyle,Skinner,male,17,5,6,82.4,"8593 East Branch St., Mooresville, NC 28115"
25,Colin,Cohen,male,14,1,10,83.8,"23 Lakewood Street, Lake Worth, FL 33460"
26,Solomon,Mcpherson,male,15,5,18,94.5,"7465 North Pearl St., Massapequa Park, NY 11762"
27,Ulla,Warren,female,18,1,16,83.5,"89 Fairview Avenue, Hopkins, MN 55343"
28,Tyler,Collier,male,16,1,9,69.7,"65 Lookout Street, Marshfield, WI 54449"
29,Emma,Mccall,female,16,2,13,91.1,"854 Sussex Street, Westford, MA 01886"
...,...,...,...,...,...,...,...,...
1976,Armando,Mcclure,male,19,2,14,93.2,"23 Hall Road, Hagerstown, MD 21740"
1977,Haley,Mcgowan,female,17,3,16,90.4,"4 Wellington Street, Saint Louis, MO 63109"
1978,Fritz,Rojas,male,17,5,13,79.5,"16 East Edgewood St., Ashtabula, OH 44004"
1979,Allistair,Boyer,male,14,3,10,74.2,"9373 Helen Drive, Leland, NC 28451"
1980,Ella,Patterson,female,16,1,8,68.0,"999 Nicolls Avenue, Oviedo, FL 32765"
1981,Felix,Freeman,male,15,4,11,75.2,"671 Division Ave., Vineland, NJ 08360"
1982,Dean,Oneil,male,16,2,8,74.5,"653 East Saxton Lane, Framingham, MA 01701"
1983,Quinlan,Hawkins,male,14,3,18,85.6,"9437 Longbranch Street, Rockville, MD 20850"
1984,Kiara,Lott,female,17,2,12,82.7,"7110 Ridge Road, Jacksonville, NC 28540"
1985,Kai,Woodard,female,17,5,17,100.0,"37 Addison St., Eastpointe, MI 48021"
1986,Maxine,Raymond,female,17,4,19,91.9,"739 Thomas Court, Memphis, TN 38106"
1987,Leah,Lawrence,female,15,5,15,100.0,"652 Pine Drive, Mountain View, CA 94043"
1988,Kalia,Lewis,female,18,1,6,61.4,"557 Theatre Lane, Green Cove Springs, FL 32043"
1989,Anthony,Palmer,male,14,1,14,93.1,"914 NW. Lawrence Street, Lawrenceville, GA 30043"
1990,Joshua,Randolph,male,15,1,4,72.7,"9632 NE. Lakeshore St., Riverside, NJ 08075"
1991,Akeem,Luna,male,15,4,6,74.4,"750 Adams Drive, Goldsboro, NC 27530"
1992,Indigo,Mccoy,female,19,2,14,91.3,"9652 Columbia Ave., Chattanooga, TN 37421"
1993,Price,Wall,male,15,5,11,78.6,"8672 S. 53rd Drive, Waterford, MI 48329"
1994,Quinn,Patterson,male,15,1,14,78.0,"634 Cedar Swamp Ave., Burbank, IL 60459"
1995,John,Ford,male,14,2,14,91.2,"64 Devonshire Street, Orange Park, FL 32065"
1996,Adena,Battle,female,17,2,8,70.2,"9272 Elizabeth Drive, Londonderry, NH 03053"
1997,Craig,Obrien,male,16,3,7,64.9,"524 Park Ave., Hollywood, FL 33020"
1998,Isabelle,Barber,female,14,5,9,78.5,"955 Glen Ridge Rd., Plattsburgh, NY 12901"
1999,Risa,Watson,female,14,2,10,74.3,"37 Augusta Lane, Montgomery Village, MD 20886"
2000,Emerson,Gill,male,17,5,5,67.5,"75 Wild Horse Street, Panama City, FL 32404"
2001,Cody,Shepherd,male,19,1,8,80.1,"982 West Street, Alexandria, VA 22304"
2002,Geraldine,Peterson,female,16,4,18,100.0,"78 Morris Street, East Northport, NY 11731"
2003,Mercedes,Leon,female,18,3,14,84.9,"30 Glenridge Rd., Bountiful, UT 84010"
2004,Lucius,Rowland,male,16,1,7,69.1,"342 West Meadowbrook Lane, Helena, MT 59601"
2005,Linus,Morris,male,19,4,10,79.6,"81 Homestead Drive, Voorhees, NJ 08043"

### Exercise 2:

Using the dataframe in the previous exercise, select all the rows where students received a grade lower than 60 (they need a teacher conference on how to improve for the next test).

In [20]:
#finds rows where the grade is less than or equal to 100
dupedf.loc[dupedf['grade'] <= 60]

,fname,lname,gender,age,exercise,hours,grade,address
340,Abbot,Hall,male,16,4,3,58.9,"84 Rock Creek Lane, Durham, NC 27703"
410,Linda,Baldwin,female,16,5,2,59.0,"970 SW. Second Ave., Cedar Falls, IA 50613"
556,Lacey,Nieves,female,18,1,2,57.9,"38 West Brickyard Avenue, Roslindale, MA 02131"
664,Alika,Poole,female,19,2,16,32.0,"9282 Purple Finch Lane, Lexington, NC 27292"
672,Ciaran,Gay,male,19,4,3,59.3,"157 Bridge Street, Corona, NY 11368"
700,Steven,Sherman,male,18,1,2,60.0,"8029 Depot Street, Port Charlotte, FL 33952"
972,Keegan,Rasmussen,male,19,4,3,43.0,"876 East Pilgrim Street, Chelmsford, MA 01824"
1068,Isaiah,Harrington,male,17,1,4,58.9,"47 Mill Pond St., Haines City, FL 33844"
1207,Selma,Stout,female,19,2,3,59.4,"5 Pierce St., Chester, PA 19013"
1237,Willa,Byers,female,14,2,4,59.2,"9466 Wayne Lane, Torrington, CT 06790"
1494,Jenna,Wagner,female,16,1,3,56.3,"8829 Shore Dr., Hopewell Junction, NY 12533"
1876,Levi,Coleman,male,19,3,3,55.9,"9453 Laurel Street, Jersey City, NJ 07302"
1888,Fitzgerald,Goff,male,18,1,4,59.8,"3 West Shipley Rd., Langhorne, PA 19047"
1916,Gail,Mcneil,female,17,2,3,56.1,"8409A Spruce St., Fishers, IN 46037"
1930,Xanthus,Mcneil,male,16,3,4,59.8,"226 Redwood Lane, Boynton Beach, FL 33435"

In [34]:
dupedf.loc[dupedf['grade'] < 60]

,fname,lname,gender,age,exercise,hours,grade,address
340,Abbot,Hall,male,16,4,3,58.9,"84 Rock Creek Lane, Durham, NC 27703"
410,Linda,Baldwin,female,16,5,2,59.0,"970 SW. Second Ave., Cedar Falls, IA 50613"
556,Lacey,Nieves,female,18,1,2,57.9,"38 West Brickyard Avenue, Roslindale, MA 02131"
664,Alika,Poole,female,19,2,16,32.0,"9282 Purple Finch Lane, Lexington, NC 27292"
672,Ciaran,Gay,male,19,4,3,59.3,"157 Bridge Street, Corona, NY 11368"
972,Keegan,Rasmussen,male,19,4,3,43.0,"876 East Pilgrim Street, Chelmsford, MA 01824"
1068,Isaiah,Harrington,male,17,1,4,58.9,"47 Mill Pond St., Haines City, FL 33844"
1207,Selma,Stout,female,19,2,3,59.4,"5 Pierce St., Chester, PA 19013"
1237,Willa,Byers,female,14,2,4,59.2,"9466 Wayne Lane, Torrington, CT 06790"
1494,Jenna,Wagner,female,16,1,3,56.3,"8829 Shore Dr., Hopewell Junction, NY 12533"
1876,Levi,Coleman,male,19,3,3,55.9,"9453 Laurel Street, Jersey City, NJ 07302"
1888,Fitzgerald,Goff,male,18,1,4,59.8,"3 West Shipley Rd., Langhorne, PA 19047"
1916,Gail,Mcneil,female,17,2,3,56.1,"8409A Spruce St., Fishers, IN 46037"
1930,Xanthus,Mcneil,male,16,3,4,59.8,"226 Redwood Lane, Boynton Beach, FL 33435"

### Exercise 3:

Using the dataframe from Exercise 1, select all the rows where a student received a grade of 100 and change their grade to 103 (extra credit!).

In [27]:
#replacing values with new value
dupedf.loc[dupedf['grade'] == 100, 'new_grade'] = 103
dupedf

,fname,lname,gender,age,exercise,hours,grade,address,Grades,new_grade
0,Marcia,Pugh,female,17,3,10,82.4,"9253 Richardson Road, Matawan, NJ 07747",NaN,NaN
1,Kadeem,Morrison,male,18,4,4,78.2,"33 Spring Dr., Taunton, MA 02780",NaN,NaN
2,Nash,Powell,male,18,5,9,79.3,"41 Hill Avenue, Mentor, OH 44060",NaN,NaN
3,Noelani,Wagner,female,14,2,7,83.2,"8839 Marshall St., Miami, FL 33125",NaN,NaN
4,Noelani,Cherry,female,18,4,15,87.4,"8304 Charles Rd., Lewis Center, OH 43035",NaN,NaN
5,Neil,Whitley,male,16,5,16,88.7,"40 Washington Ave., Bloomfield, NJ 07003",NaN,NaN
6,Nelle,Golden,female,17,1,9,80.2,"9768 Hanover Dr., Meadville, PA 16335",NaN,NaN
7,Armando,Hoffman,male,17,5,18,95.1,"360 Manor Drive, Northville, MI 48167",NaN,NaN
8,Illiana,Rojas,female,15,5,9,76.5,"9425 Studebaker Dr., Thibodaux, LA 70301",NaN,NaN
9,Neil,Wooten,male,15,3,15,89.7,"400 Bridge Court, Soddy Daisy, TN 37379",NaN,NaN
10,Daquan,Alvarez,male,16,2,13,85.2,"9028 Arnold Circle, Elizabeth, NJ 07202",NaN,NaN
11,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013",NaN,NaN
12,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911",NaN,NaN
13,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801",NaN,NaN
14,Lareina,Poole,female,18,1,14,87.6,"59 Court Dr., Waxhaw, NC 28173",NaN,NaN
15,Medge,Mccarthy,female,15,1,8,75.8,"609 Warren Court, Prior Lake, MN 55372",NaN,NaN
16,Kibo,Gates,male,16,1,10,88.2,"24 Vernon Street, Helena, MT 59601",NaN,NaN
17,Libby,Guzman,female,19,1,19,100.0,"666 S. Pennington Rd., Dover, NH 03820",103.0,103.0
18,Shelly,Rosario,female,18,4,13,84.3,"571 Miles Street, Flowery Branch, GA 30542",NaN,NaN
19,Lane,Tate,male,19,4,11,84.2,"4 Old Westport St., Glen Burnie, MD 21060",NaN,NaN
20,Isadora,Case,female,18,3,11,79.1,"44 Ocean Lane, Appleton, WI 54911",NaN,NaN
21,Maggy,Whitfield,female,15,1,15,90.5,"2 Henry Ave., Palm Bay, FL 32907",NaN,NaN
22,Elton,Wagner,male,16,2,9,71.0,"98 Indian Spring St., Athens, GA 30605",NaN,NaN
23,Lance,Benjamin,male,14,5,18,90.3,"55 Creek Dr., Lorton, VA 22079",NaN,NaN
24,Kyle,Skinner,male,17,5,6,82.4,"8593 East Branch St., Mooresville, NC 28115",NaN,NaN
25,Colin,Cohen,male,14,1,10,83.8,"23 Lakewood Street, Lake Worth, FL 33460",NaN,NaN
26,Solomon,Mcpherson,male,15,5,18,94.5,"7465 North Pearl St., Massapequa Park, NY 11762",NaN,NaN
27,Ulla,Warren,female,18,1,16,83.5,"89 Fairview Avenue, Hopkins, MN 55343",NaN,NaN
28,Tyler,Collier,male,16,1,9,69.7,"65 Lookout Street, Marshfield, WI 54449",NaN,NaN
29,Emma,Mccall,female,16,2,13,91.1,"854 Sussex Street, Westford, MA 01886",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2008,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013",NaN,NaN
2009,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911",NaN,NaN
2010,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801",NaN,NaN
2011,Lareina,Poole,female,18,1,14,87.6,"59 Court Dr., Waxhaw, NC 28173",NaN,NaN
2012,Medge,Mccarthy,female,15,1,8,75.8,"609 Warren Court, Prior Lake, MN 55372",NaN,NaN
2013,Kibo,Gates,male,16,1,10,88.2,"24 Vernon Street, Helena, MT 59601",NaN,NaN
2014,Libby,Guzman,female,19,1,19,100.0,"666 S. Pennington Rd., Dover, NH 03820",103.0,103.0
2015,Shelly,Rosario,female,18,4,13,84.3,"571 Miles Street, Flowery Branch, GA 30542",NaN,NaN
2016,Lane,Tate,male,19,4,11,84.2,"4 Old Westport St., Glen Burnie, MD 21060",NaN,NaN
2017,Isadora,Case,female,18,3,11,79.1,"44 Ocean Lane, Appleton, WI 54911",NaN,NaN
2018,Maggy,Whitfield,female,15,1,15,90.5,"2 Henry Ave., Palm Bay, FL 32907",NaN,NaN
2019,Elton,Wagner,male,16,2,9,71.0,"98 Indian Spring St., Athens, GA 30605",NaN,NaN
2020,Lance,Benjamin,male,14,5,18,90.3,"55 Creek Dr., Lorton, VA 22079",NaN,NaN
2021,Kyle,Skinner,male,17,5,6,82.4,"8593 East Branch St., Mooresville, NC 28115",NaN,NaN
2022,Colin,Cohen,male,14,1,10,83.8,"23 Lakewood Street, Lake Worth, FL 33460",NaN,NaN
2023,Solomon,Mcpherson,male,15,5,18,94.5,"7465 North Pearl St., Massapequa Park, NY 11762",NaN,NaN
2024,Marcia,Pugh,female,17,3,10,82.4,"9253 Richardson Road, Matawan, NJ 07747",NaN,NaN
2025,Kadeem,Morrison,male,18,4,4,78.2,"33 Spring Dr., Taunton, MA 02780",NaN,NaN
2026,Nash,Powell,male,18,5,9,79.3,"41 Hill Avenue, Mentor, OH 44060",NaN,NaN
2027,Noelani,Wagner,female,14,2,7,83.2,"8839 Marshall St., Miami, FL 33125",NaN,NaN
2028,Noelani,Cherry,female,18,4,15,87.4,"8304 Charles Rd., Lewis Center, OH 43035",NaN,NaN
2029,Neil,Whitley,male,16,5,16,88.7,"40 Washington Ave., Bloomfield, NJ 07003",NaN,NaN
2030,Nelle,Golden,female,17,1,9,80.2,"9768 Hanover Dr., Meadville, PA 16335",NaN,NaN
2031,Armando,Hoffman,male,17,5,18,95.1,"360 Manor Drive, Northville, MI 48167",NaN,NaN
2032,Illiana,Rojas,female,15,5,9,76.5,"9425 Studebaker Dr., Thibodaux, LA 70301",NaN,NaN
2033,Neil,Wooten,male,15,3,15,89.7,"400 Bridge Court, Soddy Daisy, TN 37379",NaN,NaN
2034,Daquan,Alvarez,male,16,2,13,85.2,"9028 Arnold Circle, Elizabeth, NJ 07202",NaN,NaN
2035,Nola,Velazquez,female,15,2,10,75.3,"72 Bradford Dr., Carlisle, PA 17013",NaN,NaN
2036,Quinn,Warren,female,14,4,12,80.7,"760 Smith Street, Appleton, WI 54911",NaN,NaN
2037,Frances,Velasquez,female,15,2,15,84.2,"57 Bridge St., Tupelo, MS 38801",NaN,NaN

### Exercise 4:

Load in the "travel_times.csv" file as a dataframe. Drop the "Comments" column. Then remove rows from the dataframe that have missing values and assign the resulting dataframe as a new variable.

In [49]:
#load csv file data with headers

location = "datasets/datasets_travel_times.csv"
travel_df = pd.read_csv(location)
travel_df.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Comments
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,NaN
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN

In [50]:
travel_df.drop('Comments', axis=1, inplace =True) #0=row axis and 1=column
travel_df.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No

In [51]:
travel_df_no_missing = travel_df.dropna()
travel_df_no_missing

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All
6,1/2/2012,17:31,Monday,Home,51.37,123.2,82.9,87.3,-,37.2,35.3,No
7,1/2/2012,07:34,Monday,GSK,49.01,128.3,77.5,85.9,-,37.9,34.3,No
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No
11,12/21/2011,07:45,Wednesday,GSK,51.77,124.8,71.7,78.9,8.89,43.3,39.4,No
12,12/20/2011,16:05,Tuesday,Home,51.45,130.1,75.2,82.7,8.89,41.1,37.3,No
13,12/20/2011,06:04,Tuesday,GSK,49.01,119.0,77.4,82.0,8.89,38.0,35.9,No
14,12/19/2011,16:18,Monday,Home,51.04,132.2,77.5,83.5,8.89,39.5,36.7,No
15,12/19/2011,07:34,Monday,GSK,52.00,137.8,76.5,87.8,8.89,40.8,35.5,No
16,12/16/2011,12:22,Friday,Home,51.05,128.4,86.9,90.6,9.08,35.2,33.8,No
17,12/16/2011,07:21,Friday,GSK,49.04,124.6,71.1,80.2,9.08,41.4,36.7,No
18,12/15/2011,16:14,Thursday,Home,51.06,126.9,80.5,84.9,9.08,38.1,36.1,No
19,12/15/2011,07:19,Thursday,GSK,51.68,123.5,68.1,75.8,9.08,45.6,40.9,No
20,12/14/2011,16:20,Wednesday,Home,51.04,123.4,75.1,79.4,9.08,40.8,38.6,No
21,12/14/2011,07:23,Wednesday,GSK,51.67,123.5,76.6,82.7,9.08,40.5,37.5,No
22,12/13/2011,17:43,Tuesday,Home,51.15,130.6,74.8,82.4,9.08,41.0,37.2,No
23,12/13/2011,07:25,Tuesday,GSK,49.19,126.1,65.4,74.2,9.08,45.1,39.8,No
24,12/12/2011,07:20,Monday,GSK,49.02,126.1,65.7,74.0,9.76,44.8,39.7,No
25,12/9/2011,12:04,Friday,Home,51.14,126.8,87.3,90.2,9.76,35.2,34.0,No
26,12/9/2011,07:22,Friday,GSK,51.69,128.4,74.0,77.3,9.76,41.9,40.1,No
27,12/8/2011,17:41,Thursday,Home,51.07,125.0,74.6,81.5,9.76,41.1,37.6,No
28,12/8/2011,07:14,Thursday,GSK,51.63,134.4,76.5,84.3,9.76,40.5,36.7,No
29,12/7/2011,16:12,Wednesday,Home,51.10,126.5,79.9,85.6,9.76,38.4,35.8,No
30,12/7/2011,07:18,Wednesday,GSK,51.64,124.6,73.6,82.0,9.76,42.1,37.8,No
31,12/6/2011,17:24,Tuesday,Home,51.25,123.5,77.3,81.9,9.16,39.8,37.6,No
32,12/6/2011,07:24,Tuesday,GSK,51.64,122.3,69.3,74.7,9.16,44.7,41.5,No
33,12/5/2011,16:18,Monday,Home,50.18,124.0,71.0,79.5,9.16,42.4,37.9,No
42,11/24/2011,16:15,Thursday,Home,51.49,126.6,74.0,82.8,9.3,41.8,37.3,No
43,11/24/2011,07:23,Thursday,GSK,51.69,124.9,73.3,80.3,9.3,42.3,38.6,No
...,...,...,...,...,...,...,...,...,...,...,...,...
172,8/9/2011,08:15,Tuesday,GSK,49.08,134.8,60.5,67.2,8.54,48.7,43.8,No
173,8/8/2011,17:05,Monday,Home,52.35,127.5,76.9,84.2,8.54,40.9,37.3,No
174,8/8/2011,08:07,Monday,GSK,49.25,126.3,68.5,78.2,8.54,43.1,37.8,No
175,8/5/2011,17:00,Friday,Home,51.94,126.7,74.5,82.6,8.48,41.9,37.7,No
176,8/5/2011,08:20,Friday,GSK,49.13,123.9,74.1,79.9,8.48,39.8,36.9,No
177,8/4/2011,17:38,Thursday,Home,50.96,131.9,70.3,78.5,8.48,43.5,38.9,No
178,8/4/2011,08:17,Thursday,GSK,49.12,122.4,71.5,77.3,8.48,41.2,38.2,No
179,8/3/2011,17:14,Wednesday,Home,51.64,125.0,72.2,78.7,8.48,42.9,39.4,No
180,8/3/2011,08:06,Wednesday,GSK,49.06,121.9,71.5,78.7,8.48,41.2,37.4,No
181,8/2/2011,17:22,Tuesday,Home,51.16,124.2,76.3,83.2,8.48,40.2,36.9,No
182,8/2/2011,07:38,Tuesday,GSK,53.48,124.9,68.8,78.8,8.48,46.7,40.7,No
183,7/29/2011,20:31,Friday,Home,50.68,135.6,107.7,110.4,8.45,28.2,27.6,Yes
184,7/29/2011,08:22,Friday,GSK,49.07,121.1,73.2,77.7,8.45,40.2,37.9,No
185,7/28/2011,17:46,Thursday,Home,51.09,128.5,76.0,84.8,8.45,40.3,36.2,No
186,7/28/2011,08:11,Thursday,GSK,49.11,120.1,69.1,73.1,8.45,42.6,40.3,No
187,7/27/2011,17:24,Wednesday,Home,50.98,124.9,68.3,71.9,8.45,44.8,42.6,No
188,7/27/2011,08:15,Wednesday,GSK,48.82,124.5,70.4,77.8,8.45,41.6,37.6,No
189,7/26/2011,17:15,Tuesday,Home,51.28,122.1,43.7,51.5,8.45,70.5,59.8,No
190,7/26/2011,08:11,Tuesday,GSK,49.16,122.6,71.9,76.8,8.45,41.0,38.4,No
191,7/25/2011,16:59,Monday,Home,51.05,126.6,70.4,78.8,8.45,51.1,38.9,No
192,7/25/2011,08:06,Monday,GSK,48.32,121.2,63.4,78.4,8.45,45.7,37.0,No
193,7/22/2011,16:47,Friday,Home,51.24,126.3,75.8,81.8,8.28,40.6,37.6,No
194,7/22/2011,08:28,Friday,GSK,51.05,123.3,88.9,96.7,8.28,34.5,31.7,Yes
195,7/21/2011,07:59,Thursday,GSK,48.35,129.3,81.5,89.0,8.28,35.6,32.6,Yes
196,7/20/2011,17:17,Wednesday,Home,53.47,124.0,58.6,71.0,7.89,54.8,45.2,No
197,7/20/2011,08:24,Wednesday,GSK,48.50,125.8,75.7,87.3,7.89,38.5,33.3,Yes
198,7/19/2011,17:17,Tuesday,Home,51.16,126.7,92.2,102.6,7.89,33.3,29.9,Yes
199,7/19/2011,08:11,Tuesday,GSK,50.96,124.3,82.3,96.4,7.89,37.2,31.7,Yes
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No
201,7/14/2011,08:03,Thursday,GSK,50.90,123.7,76.2,95.1,7.89,40.1,32.1,Yes

### Exercise 5:

Using the dataframe from the exercise above (w/ no missing values), create bins that will categorize the AvgSpeed column as "slow" or "fast", and make a new column called "Speed" to hold those new values. Values less than 75 are "slow" and everything above is "fast".

In [52]:
#Define bins as 0-74, 75-107
bins = [0,75,107]

# Create names for the four groups
group_names = ['slow', 'fast']

#make new column with letter grades
travel_df['Speed'] = pd.cut(travel_df['AvgSpeed'], bins, labels=group_names)
travel_df.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,fast
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,fast
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,fast
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,slow
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,fast

In [9]:
#find rows equal to 75
travel_df.loc[travel_df['AvgSpeed'] >=75]

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Comments
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN
5,1/3/2012,07:57,Tuesday,GSK,51.80,135.8,84.5,88.8,NaN,36.8,35.0,No,NaN
6,1/2/2012,17:31,Monday,Home,51.37,123.2,82.9,87.3,-,37.2,35.3,No,NaN
7,1/2/2012,07:34,Monday,GSK,49.01,128.3,77.5,85.9,-,37.9,34.3,No,NaN
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No,NaN
12,12/20/2011,16:05,Tuesday,Home,51.45,130.1,75.2,82.7,8.89,41.1,37.3,No,NaN
13,12/20/2011,06:04,Tuesday,GSK,49.01,119.0,77.4,82.0,8.89,38.0,35.9,No,NaN
14,12/19/2011,16:18,Monday,Home,51.04,132.2,77.5,83.5,8.89,39.5,36.7,No,NaN
15,12/19/2011,07:34,Monday,GSK,52.00,137.8,76.5,87.8,8.89,40.8,35.5,No,Put snow tires on
16,12/16/2011,12:22,Friday,Home,51.05,128.4,86.9,90.6,9.08,35.2,33.8,No,NaN
18,12/15/2011,16:14,Thursday,Home,51.06,126.9,80.5,84.9,9.08,38.1,36.1,No,NaN
20,12/14/2011,16:20,Wednesday,Home,51.04,123.4,75.1,79.4,9.08,40.8,38.6,No,NaN
21,12/14/2011,07:23,Wednesday,GSK,51.67,123.5,76.6,82.7,9.08,40.5,37.5,No,NaN
25,12/9/2011,12:04,Friday,Home,51.14,126.8,87.3,90.2,9.76,35.2,34.0,No,NaN
28,12/8/2011,07:14,Thursday,GSK,51.63,134.4,76.5,84.3,9.76,40.5,36.7,No,NaN
29,12/7/2011,16:12,Wednesday,Home,51.10,126.5,79.9,85.6,9.76,38.4,35.8,No,NaN
31,12/6/2011,17:24,Tuesday,Home,51.25,123.5,77.3,81.9,9.16,39.8,37.6,No,NaN
35,12/1/2011,07:24,Thursday,GSK,51.38,124.6,80.1,84.4,NaN,38.5,36.5,No,NaN
37,11/30/2011,07:19,Wednesday,GSK,51.71,125.6,76.3,81.8,NaN,40.7,37.9,No,NaN
46,11/22/2011,16:15,Tuesday,Home,51.49,129.6,78.6,83.8,9.3,39.3,36.9,No,NaN
47,11/22/2011,07:27,Tuesday,GSK,51.65,128.6,76.1,82.6,9.3,40.7,37.5,No,NaN
58,11/10/2011,16:11,Thursday,Home,51.07,129.8,75.2,82.6,9.53,40.8,37.1,No,NaN
62,11/8/2011,17:24,Tuesday,Home,50.75,131.3,89.5,93.5,9.35,34.3,32.6,Yes,NaN
64,11/7/2011,16:05,Monday,Home,51.06,127.4,80.4,85.2,9.35,38.1,36.0,No,NaN
66,11/4/2011,12:12,Friday,Home,51.03,128.4,82.2,89.7,9.35,37.2,34.1,No,NaN
67,11/4/2011,08:16,Friday,GSK,51.81,130.2,82.1,85.0,9.35,37.9,36.6,No,NaN
68,11/3/2011,17:00,Thursday,Home,51.07,130.3,75.8,81.7,8.32,40.4,37.5,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,9/12/2011,17:04,Monday,Home,51.43,131.1,75.1,79.5,8.5,40.6,38.8,No,NaN
133,9/6/2011,16:27,Tuesday,Home,52.88,131.6,95.4,98.3,8.5,33.3,32.3,Yes,Took 407 all the way (to McMaster)
134,9/6/2011,07:50,Tuesday,GSK,54.36,132.5,95.1,98.0,8.5,34.3,33.3,Yes,NaN
135,9/2/2011,17:07,Friday,Home,51.17,129.7,77.7,87.9,8.5,39.5,34.9,No,NaN
136,9/2/2011,07:39,Friday,GSK,51.65,132.7,82.6,91.4,8.5,37.5,33.9,No,NaN
137,9/1/2011,17:33,Thursday,Home,52.42,128.9,81.6,88.0,8.5,38.5,35.7,No,NaN
143,8/29/2011,17:11,Monday,Home,51.04,131.0,75.5,84.1,8.5,40.5,36.4,No,NaN
145,8/26/2011,16:29,Friday,Home,50.88,132.7,81.1,86.9,8.54,37.6,35.2,No,NaN
146,8/26/2011,07:49,Friday,GSK,49.01,129.1,76.3,83.3,8.54,38.6,35.3,No,NaN
148,8/25/2011,09:09,Thursday,GSK,50.45,133.5,106.8,111.1,8.54,28.3,27.3,Yes,NaN
149,8/24/2011,16:47,Wednesday,Home,51.01,132.9,79.6,86.1,8.54,38.5,38.5,No,NaN
151,8/23/2011,17:23,Tuesday,Home,51.22,129.7,79.7,84.5,8.54,38.5,36.4,No,NaN
153,8/22/2011,16:44,Monday,Home,51.12,126.8,77.9,85.2,8.54,39.6,36.0,No,NaN
155,8/19/2011,17:42,Friday,Home,51.09,126.5,78.1,81.6,8.37,39.3,37.6,No,NaN
161,8/16/2011,17:27,Tuesday,Home,51.14,133.4,82.4,87.0,8.37,37.2,35.3,No,NaN
162,8/16/2011,08:15,Tuesday,GSK,49.14,131.7,75.0,80.2,8.37,39.3,36.7,No,NaN
163,8/15/2011,17:38,Monday,Home,51.11,132.3,78.0,83.7,8.37,39.3,36.7,No,NaN
166,8/12/2011,08:05,Friday,GSK,49.02,128.4,76.7,82.9,8.54,38.4,35.5,No,Must be Friday
167,8/11/2011,17:25,Thursday,Home,51.18,133.6,80.7,86.0,8.54,38.0,35.7,No,NaN
173,8/8/2011,17:05,Monday,Home,52.35,127.5,76.9,84.2,8.54,40.9,37.3,No,NaN
181,8/2/2011,17:22,Tuesday,Home,51.16,124.2,76.3,83.2,8.48,40.2,36.9,No,NaN
183,7/29/2011,20:31,Friday,Home,50.68,135.6,107.7,110.4,8.45,28.2,27.6,Yes,NaN
185,7/28/2011,17:46,Thursday,Home,51.09,128.5,76.0,84.8,8.45,40.3,36.2,No,NaN
193,7/22/2011,16:47,Friday,Home,51.24,126.3,75.8,81.8,8.28,40.6,37.6,No,NaN
194,7/22/2011,08:28,Friday,GSK,51.05,123.3,88.9,96.7,8.28,34.5,31.7,Yes,NaN
195,7/21/2011,07:59,Thursday,GSK,48.35,129.3,81.5,89.0,8.28,35.6,32.6,Yes,NaN
197,7/20/2011,08:24,Wednesday,GSK,48.50,125.8,75.7,87.3,7.89,38.5,33.3,Yes,NaN
198,7/19/2011,17:17,Tuesday,Home,51.16,126.7,92.2,102.6,7.89,33.3,29.9,Yes,NaN
199,7/19/2011,08:11,Tuesday,GSK,50.96,124.3,82.3,96.4,7.89,37.2,31.7,Yes,NaN
201,7/14/2011,08:03,Thursday,GSK,50.90,123.7,76.2,95.1,7.89,40.1,32.1,Yes,NaN

In [53]:
#find rows equal to 75
travel_df.loc[travel_df['AvgSpeed'] <=75]

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,slow
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No,slow
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No,slow
11,12/21/2011,07:45,Wednesday,GSK,51.77,124.8,71.7,78.9,8.89,43.3,39.4,No,slow
17,12/16/2011,07:21,Friday,GSK,49.04,124.6,71.1,80.2,9.08,41.4,36.7,No,slow
19,12/15/2011,07:19,Thursday,GSK,51.68,123.5,68.1,75.8,9.08,45.6,40.9,No,slow
22,12/13/2011,17:43,Tuesday,Home,51.15,130.6,74.8,82.4,9.08,41.0,37.2,No,slow
23,12/13/2011,07:25,Tuesday,GSK,49.19,126.1,65.4,74.2,9.08,45.1,39.8,No,slow
24,12/12/2011,07:20,Monday,GSK,49.02,126.1,65.7,74.0,9.76,44.8,39.7,No,slow
26,12/9/2011,07:22,Friday,GSK,51.69,128.4,74.0,77.3,9.76,41.9,40.1,No,slow
27,12/8/2011,17:41,Thursday,Home,51.07,125.0,74.6,81.5,9.76,41.1,37.6,No,slow
30,12/7/2011,07:18,Wednesday,GSK,51.64,124.6,73.6,82.0,9.76,42.1,37.8,No,slow
32,12/6/2011,07:24,Tuesday,GSK,51.64,122.3,69.3,74.7,9.16,44.7,41.5,No,slow
33,12/5/2011,16:18,Monday,Home,50.18,124.0,71.0,79.5,9.16,42.4,37.9,No,slow
34,12/1/2011,16:15,Thursday,Home,51.55,129.6,74.2,83.7,NaN,41.7,36.9,No,slow
36,11/30/2011,16:11,Wednesday,Home,51.09,128.7,71.5,76.7,NaN,42.9,39.9,No,slow
38,11/29/2011,16:52,Tuesday,Home,51.00,121.4,68.4,75.4,NaN,44.7,40.6,No,slow
39,11/29/2011,07:23,Tuesday,GSK,51.74,112.2,55.3,61.0,NaN,56.2,50.9,No,slow
40,11/28/2011,16:16,Monday,Home,51.05,128.2,72.4,78.8,NaN,42.3,38.9,No,slow
41,11/28/2011,07:26,Monday,GSK,51.63,127.1,71.0,75.5,NaN,43.6,41.1,No,slow
42,11/24/2011,16:15,Thursday,Home,51.49,126.6,74.0,82.8,9.3,41.8,37.3,No,slow
43,11/24/2011,07:23,Thursday,GSK,51.69,124.9,73.3,80.3,9.3,42.3,38.6,No,slow
44,11/23/2011,16:17,Wednesday,Home,60.32,129.4,68.9,74.6,9.3,52.5,48.5,No,slow
45,11/23/2011,07:22,Wednesday,GSK,51.60,126.4,67.3,73.6,9.3,46.0,42.1,No,slow
48,11/21/2011,16:50,Monday,Home,51.31,123.1,60.9,67.2,10.05,50.6,45.8,No,slow
49,11/21/2011,07:24,Monday,GSK,52.25,127.3,38.1,50.3,10.05,82.3,62.4,No,slow
50,11/17/2011,16:16,Thursday,Home,51.16,127.6,72.4,77.4,10.05,42.4,39.6,No,slow
51,11/17/2011,07:42,Thursday,GSK,51.67,127.0,70.9,77.7,10.05,43.7,39.9,No,slow
52,11/16/2011,16:13,Wednesday,Home,51.12,125.1,65.0,73.1,9.53,47.2,41.9,No,slow
53,11/16/2011,07:26,Wednesday,GSK,51.70,129.8,73.4,80.4,9.53,42.3,38.6,No,slow
...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,8/17/2011,08:10,Wednesday,GSK,49.10,124.8,67.9,76.2,8.37,43.4,38.7,No,slow
162,8/16/2011,08:15,Tuesday,GSK,49.14,131.7,75.0,80.2,8.37,39.3,36.7,No,slow
164,8/15/2011,08:15,Monday,GSK,49.20,124.7,71.3,75.7,8.37,41.4,39.0,No,slow
165,8/12/2011,17:25,Friday,Home,55.57,127.7,69.6,77.1,8.54,47.9,43.2,No,slow
168,8/11/2011,08:13,Thursday,GSK,48.99,125.5,68.3,79.5,8.54,43.0,37.0,No,slow
169,8/10/2011,17:14,Wednesday,Home,51.03,127.4,73.5,79.3,8.54,41.7,38.6,No,slow
170,8/10/2011,08:13,Wednesday,GSK,48.98,124.8,72.8,78.8,8.54,40.4,37.3,No,slow
171,8/9/2011,17:13,Tuesday,Home,51.15,127.1,72.1,82.3,8.54,42.5,37.3,No,slow
172,8/9/2011,08:15,Tuesday,GSK,49.08,134.8,60.5,67.2,8.54,48.7,43.8,No,slow
174,8/8/2011,08:07,Monday,GSK,49.25,126.3,68.5,78.2,8.54,43.1,37.8,No,slow
175,8/5/2011,17:00,Friday,Home,51.94,126.7,74.5,82.6,8.48,41.9,37.7,No,slow
176,8/5/2011,08:20,Friday,GSK,49.13,123.9,74.1,79.9,8.48,39.8,36.9,No,slow
177,8/4/2011,17:38,Thursday,Home,50.96,131.9,70.3,78.5,8.48,43.5,38.9,No,slow
178,8/4/2011,08:17,Thursday,GSK,49.12,122.4,71.5,77.3,8.48,41.2,38.2,No,slow
179,8/3/2011,17:14,Wednesday,Home,51.64,125.0,72.2,78.7,8.48,42.9,39.4,No,slow
180,8/3/2011,08:06,Wednesday,GSK,49.06,121.9,71.5,78.7,8.48,41.2,37.4,No,slow
182,8/2/2011,07:38,Tuesday,GSK,53.48,124.9,68.8,78.8,8.48,46.7,40.7,No,slow
184,7/29/2011,08:22,Friday,GSK,49.07,121.1,73.2,77.7,8.45,40.2,37.9,No,slow
186,7/28/2011,08:11,Thursday,GSK,49.11,120.1,69.1,73.1,8.45,42.6,40.3,No,slow
187,7/27/2011,17:24,Wednesday,Home,50.98,124.9,68.3,71.9,8.45,44.8,42.6,No,slow
188,7/27/2011,08:15,Wednesday,GSK,48.82,124.5,70.4,77.8,8.45,41.6,37.6,No,slow
189,7/26/2011,17:15,Tuesday,Home,51.28,122.1,43.7,51.5,8.45,70.5,59.8,No,slow
190,7/26/2011,08:11,Tuesday,GSK,49.16,122.6,71.9,76.8,8.45,41.0,38.4,No,slow
191,7/25/2011,16:59,Monday,Home,51.05,126.6,70.4,78.8,8.45,51.1,38.9,No,slow
192,7/25/2011,08:06,Monday,GSK,48.32,121.2,63.4,78.4,8.45,45.7,37.0,No,slow
196,7/20/2011,17:17,Wednesday,Home,53.47,124.0,58.6,71.0,7.89,54.8,45.2,No,slow
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No,slow
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,76.7,NaN,54.2,40.6,Yes,slow
203,7/12/2011,17:51,Tuesday,Home,53.28,125.8,61.6,87.6,NaN,51.9,36.5,Yes,slow
204,7/11/2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,slow

In [54]:
#find rows equal to 75
travel_df.loc[travel_df['AvgSpeed'] <=65]

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed
39,11/29/2011,07:23,Tuesday,GSK,51.74,112.2,55.3,61.0,NaN,56.2,50.9,No,slow
48,11/21/2011,16:50,Monday,Home,51.31,123.1,60.9,67.2,10.05,50.6,45.8,No,slow
49,11/21/2011,07:24,Monday,GSK,52.25,127.3,38.1,50.3,10.05,82.3,62.4,No,slow
52,11/16/2011,16:13,Wednesday,Home,51.12,125.1,65.0,73.1,9.53,47.2,41.9,No,slow
54,11/15/2011,17:36,Tuesday,Home,51.06,122.8,61.4,70.9,9.53,49.9,43.2,No,slow
56,11/14/2011,16:15,Monday,Home,51.06,119.5,64.4,70.2,9.53,47.6,43.6,No,slow
57,11/14/2011,07:19,Monday,GSK,51.66,126.4,55.2,59.1,9.53,56.1,52.5,No,slow
84,10/19/2011,17:39,Wednesday,Home,51.30,126.2,63.4,73.3,8.75,48.6,42.0,No,slow
91,10/12/2011,17:47,Wednesday,Home,51.40,114.4,59.7,65.8,8.75,51.7,46.9,No,slow
92,10/12/2011,08:28,Wednesday,GSK,50.58,128.4,59.5,67.3,8.75,51.0,45.1,Yes,slow
98,10/6/2011,08:22,Thursday,GSK,50.63,125.6,38.5,103.8,7.97,30.8,29.3,Yes,slow
116,9/21/2011,08:02,Wednesday,GSK,49.16,128.7,59.5,68.0,8.33,49.6,43.4,No,slow
126,9/13/2011,07:51,Tuesday,GSK,49.12,129.1,52.7,63.2,8.5,55.9,46.6,No,slow
130,9/8/2011,07:23,Thursday,GSK,49.25,124.7,53.5,63.1,8.5,55.2,46.9,No,slow
132,9/7/2011,07:57,Wednesday,GSK,49.08,125.1,56.5,66.5,8.5,52.1,44.3,No,slow
144,8/29/2011,07:48,Monday,GSK,49.15,124.0,63.9,74.0,8.5,46.1,39.9,No,slow
147,8/25/2011,17:39,Thursday,Home,51.23,132.8,64.2,70.6,8.54,47.9,43.5,No,slow
150,8/24/2011,07:59,Wednesday,GSK,49.07,127.1,58.5,71.5,8.54,50.3,41.1,No,slow
158,8/18/2011,08:11,Thursday,GSK,52.26,137.7,51.2,64.1,8.37,61.2,48.9,No,slow
172,8/9/2011,08:15,Tuesday,GSK,49.08,134.8,60.5,67.2,8.54,48.7,43.8,No,slow
189,7/26/2011,17:15,Tuesday,Home,51.28,122.1,43.7,51.5,8.45,70.5,59.8,No,slow
192,7/25/2011,08:06,Monday,GSK,48.32,121.2,63.4,78.4,8.45,45.7,37.0,No,slow
196,7/20/2011,17:17,Wednesday,Home,53.47,124.0,58.6,71.0,7.89,54.8,45.2,No,slow
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No,slow
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,76.7,NaN,54.2,40.6,Yes,slow
203,7/12/2011,17:51,Tuesday,Home,53.28,125.8,61.6,87.6,NaN,51.9,36.5,Yes,slow
204,7/11/2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,slow

In [55]:
#find rows equal to 75
travel_df.loc[travel_df['AvgSpeed'] <=40]

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed
49,11/21/2011,07:24,Monday,GSK,52.25,127.3,38.1,50.3,10.05,82.3,62.4,No,slow
98,10/6/2011,08:22,Thursday,GSK,50.63,125.6,38.5,103.8,7.97,30.8,29.3,Yes,slow

In [56]:
travel_df['AvgSpeed'].dtypes

dtype('float64')

### Exercise 6:

Using the dataframe in the previous exercise, make a new column called "Police" which is equal to all the values being "no" (they were never stopped by police for speeding while traveling).

In [57]:
#make new column with all no values
travel_df['Police']='No'

In [22]:
print(travel_df)

           Date StartTime  DayOfWeek GoingTo  Distance  MaxSpeed  AvgSpeed  \
0      1/6/2012     16:37     Friday    Home     51.29     127.4      78.3
1      1/6/2012     08:20     Friday     GSK     51.63     130.3      81.8
2      1/4/2012     16:17  Wednesday    Home     51.27     127.4      82.0
3      1/4/2012     07:53  Wednesday     GSK     49.17     132.3      74.2
4      1/3/2012     18:57    Tuesday    Home     51.15     136.2      83.4
5      1/3/2012     07:57    Tuesday     GSK     51.80     135.8      84.5
6      1/2/2012     17:31     Monday    Home     51.37     123.2      82.9
7      1/2/2012     07:34     Monday     GSK     49.01     128.3      77.5
8    12/23/2011     08:01     Friday     GSK     52.91     130.3      80.9
9    12/22/2011     17:19   Thursday    Home     51.17     122.3      70.6
10   12/22/2011     08:16   Thursday     GSK     49.15     129.4      74.0
11   12/21/2011     07:45  Wednesday     GSK     51.77     124.8      71.7
12   12/20/2011     16:05    Tuesday    Home     51.45     130.1      75.2
13   12/20/2011     06:04    Tuesday     GSK     49.01     119.0      77.4
14   12/19/2011     16:18     Monday    Home     51.04     132.2      77.5
15   12/19/2011     07:34     Monday     GSK     52.00     137.8      76.5
16   12/16/2011     12:22     Friday    Home     51.05     128.4      86.9
17   12/16/2011     07:21     Friday     GSK     49.04     124.6      71.1
18   12/15/2011     16:14   Thursday    Home     51.06     126.9      80.5
19   12/15/2011     07:19   Thursday     GSK     51.68     123.5      68.1
20   12/14/2011     16:20  Wednesday    Home     51.04     123.4      75.1
21   12/14/2011     07:23  Wednesday     GSK     51.67     123.5      76.6
22   12/13/2011     17:43    Tuesday    Home     51.15     130.6      74.8
23   12/13/2011     07:25    Tuesday     GSK     49.19     126.1      65.4
24   12/12/2011     07:20     Monday     GSK     49.02     126.1      65.7
25    12/9/2011     12:04     Friday    Home     51.14     126.8      87.3
26    12/9/2011     07:22     Friday     GSK     51.69     128.4      74.0
27    12/8/2011     17:41   Thursday    Home     51.07     125.0      74.6
28    12/8/2011     07:14   Thursday     GSK     51.63     134.4      76.5
29    12/7/2011     16:12  Wednesday    Home     51.10     126.5      79.9
..          ...       ...        ...     ...       ...       ...       ...
175    8/5/2011     17:00     Friday    Home     51.94     126.7      74.5
176    8/5/2011     08:20     Friday     GSK     49.13     123.9      74.1
177    8/4/2011     17:38   Thursday    Home     50.96     131.9      70.3
178    8/4/2011     08:17   Thursday     GSK     49.12     122.4      71.5
179    8/3/2011     17:14  Wednesday    Home     51.64     125.0      72.2
180    8/3/2011     08:06  Wednesday     GSK     49.06     121.9      71.5
181    8/2/2011     17:22    Tuesday    Home     51.16     124.2      76.3
182    8/2/2011     07:38    Tuesday     GSK     53.48     124.9      68.8
183   7/29/2011     20:31     Friday    Home     50.68     135.6     107.7
184   7/29/2011     08:22     Friday     GSK     49.07     121.1      73.2
185   7/28/2011     17:46   Thursday    Home     51.09     128.5      76.0
186   7/28/2011     08:11   Thursday     GSK     49.11     120.1      69.1
187   7/27/2011     17:24  Wednesday    Home     50.98     124.9      68.3
188   7/27/2011     08:15  Wednesday     GSK     48.82     124.5      70.4
189   7/26/2011     17:15    Tuesday    Home     51.28     122.1      43.7
190   7/26/2011     08:11    Tuesday     GSK     49.16     122.6      71.9
191   7/25/2011     16:59     Monday    Home     51.05     126.6      70.4
192   7/25/2011     08:06     Monday     GSK     48.32     121.2      63.4
193   7/22/2011     16:47     Friday    Home     51.24     126.3      75.8
194   7/22/2011     08:28     Friday     GSK     51.05     123.3      88.9
195   7/21/2011     07:59   Thursday     GSK     48.35     129.3      81.5
196   7/20/2011     17:17  Wednesday    Home     53.47     124.0      58.6
197   7/20/2011     08:24  Wednesday     GSK     48.50     125.8      75.7
198   7/19/2011     17:17    Tuesday    Home     51.16     126.7      92.2
199   7/19/2011     08:11    Tuesday     GSK     50.96     124.3      82.3
200   7/18/2011     08:09     Monday     GSK     54.52     125.6      49.9
201   7/14/2011     08:03   Thursday     GSK     50.90     123.7      76.2
202   7/13/2011     17:08  Wednesday    Home     51.96     132.6      57.5
203   7/12/2011     17:51    Tuesday    Home     53.28     125.8      61.6
204   7/11/2011     16:56     Monday    Home     51.73     125.0      62.8

     AvgMovingSpeed FuelEconomy  TotalTime  MovingTime Take407All  \
0              84.8         NaN       39.3        36.3         No
1              88.9         NaN       37.9        34.9         No
2              85.8         NaN       37.5        35.9         No
3              82.9         NaN       39.8        35.6         No
4              88.1         NaN       36.8        34.8         No
5              88.8         NaN       36.8        35.0         No
6              87.3           -       37.2        35.3         No
7              85.9           -       37.9        34.3         No
8              88.3        8.89       39.3        36.0         No
9              78.1        8.89       43.5        39.3         No
10             81.4        8.89       39.8        36.2         No
11             78.9        8.89       43.3        39.4         No
12             82.7        8.89       41.1        37.3         No
13             82.0        8.89       38.0        35.9         No
14             83.5        8.89       39.5        36.7         No
15             87.8        8.89       40.8        35.5         No
16             90.6        9.08       35.2        33.8         No
17             80.2        9.08       41.4        36.7         No
18             84.9        9.08       38.1        36.1         No
19             75.8        9.08       45.6        40.9         No
20             79.4        9.08       40.8        38.6         No
21             82.7        9.08       40.5        37.5         No
22             82.4        9.08       41.0        37.2         No
23             74.2        9.08       45.1        39.8         No
24             74.0        9.76       44.8        39.7         No
25             90.2        9.76       35.2        34.0         No
26             77.3        9.76       41.9        40.1         No
27             81.5        9.76       41.1        37.6         No
28             84.3        9.76       40.5        36.7         No
29             85.6        9.76       38.4        35.8         No
..              ...         ...        ...         ...        ...
175            82.6        8.48       41.9        37.7         No
176            79.9        8.48       39.8        36.9         No
177            78.5        8.48       43.5        38.9         No
178            77.3        8.48       41.2        38.2         No
179            78.7        8.48       42.9        39.4         No
180            78.7        8.48       41.2        37.4         No
181            83.2        8.48       40.2        36.9         No
182            78.8        8.48       46.7        40.7         No
183           110.4        8.45       28.2        27.6        Yes
184            77.7        8.45       40.2        37.9         No
185            84.8        8.45       40.3        36.2         No
186            73.1        8.45       42.6        40.3         No
187            71.9        8.45       44.8        42.6         No
188            77.8        8.45       41.6        37.6         No
189            51.5        8.45       70.5        59.8         No
190            76.8        8.45       41.0        38.4         No
191            78.8        8.45       51.1        38.9         No
192            78.4        8.45       45.7        37.0         No
193            81.8        8.28       40.6        37.6         No
194            96.7        8.28       34.5        31.7        Yes
195            89.0        8.28       35.6        32.6        Yes
196            71.0        7.89       54.8        45.2         No
197            87.3        7.89       38.5        33.3        Yes
198           102.6        7.89       33.3        29.9        Yes
199            96.4        7.89       37.2        31.7        Yes
200            82.4        7.89       65.5        39.7         No
201            95.1        7.89       40.1        32.1        Yes
202            76.7         NaN       54.2        40.6        Yes
203            87.6         NaN       51.9        36.5        Yes
204            92.5         NaN       49.5        33.6        Yes

                      Comments Speed Police
0                          NaN  fast     No
1                          NaN  fast     No
2                          NaN  fast     No
3                          NaN  slow     No
4                          NaN  fast     No
5                          NaN  fast     No
6                          NaN  fast     No
7                          NaN  fast     No
8                          NaN  fast     No
9                          NaN  slow     No
10                         NaN  slow     No
11                         NaN  slow     No
12                         NaN  fast     No
13                         NaN  fast     No
14                         NaN  fast     No
15           Put snow tires on  fast     No
16                         NaN  fast     No
17                         NaN  slow     No
18                         NaN  fast     No
19                         NaN  slow     No
20                         NaN  fast     No
21                         NaN  fast     No
22                         NaN  slow     No
23                         NaN  slow     No
24                         NaN  slow     No
25                         NaN  fast     No
26                         NaN  slow     No
27                         NaN  slow     No
28                         NaN  fast     No
29                         NaN  fast     No
..                         ...   ...    ...
175                        NaN  slow     No
176                        NaN  slow     No
177                        NaN  slow     No
178                        NaN  slow     No
179                        NaN  slow     No
180                        NaN  slow     No
181                        NaN  fast     No
182       Turn around on Derry  slow     No
183                        NaN   NaN     No
184                Empty roads  slow     No
185                        NaN  fast     No
186                        NaN  slow     No
187     Police slowdown on 403  slow     No
188                        NaN  slow     No
189  Accident blocked 407 exit  slow     No
190                        NaN  slow     No
191                        NaN  slow     No
192                        NaN  slow     No
193                        NaN  fast     No
194                        NaN  fast     No
195                        NaN  fast     No
196                        NaN  slow     No
197                        NaN  fast     No
198                        NaN  fast     No
199                        NaN  fast     No
200                        NaN  slow     No
201                        NaN  fast     No
202                        NaN  slow     No
203                        NaN  slow     No
204                        NaN  slow     No

[205 rows x 15 columns]

In [60]:
travel_df.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed,Police
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,fast,No
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,fast,No
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,fast,No
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,slow,No
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,fast,No

### Exercise 7:

Using the dataframe from the previous exercise, pick a method (Standard Deviation or Interquartile Range) and remove the outliers from the "FuelEconomy" column.

In [58]:
 #drop rows with any missing data
travel_df_no_missing = travel_df.dropna()
travel_df_no_missing

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed,Police
6,1/2/2012,17:31,Monday,Home,51.37,123.2,82.9,87.3,-,37.2,35.3,No,fast,No
7,1/2/2012,07:34,Monday,GSK,49.01,128.3,77.5,85.9,-,37.9,34.3,No,fast,No
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No,fast,No
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No,slow,No
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No,slow,No
11,12/21/2011,07:45,Wednesday,GSK,51.77,124.8,71.7,78.9,8.89,43.3,39.4,No,slow,No
12,12/20/2011,16:05,Tuesday,Home,51.45,130.1,75.2,82.7,8.89,41.1,37.3,No,fast,No
13,12/20/2011,06:04,Tuesday,GSK,49.01,119.0,77.4,82.0,8.89,38.0,35.9,No,fast,No
14,12/19/2011,16:18,Monday,Home,51.04,132.2,77.5,83.5,8.89,39.5,36.7,No,fast,No
15,12/19/2011,07:34,Monday,GSK,52.00,137.8,76.5,87.8,8.89,40.8,35.5,No,fast,No
16,12/16/2011,12:22,Friday,Home,51.05,128.4,86.9,90.6,9.08,35.2,33.8,No,fast,No
17,12/16/2011,07:21,Friday,GSK,49.04,124.6,71.1,80.2,9.08,41.4,36.7,No,slow,No
18,12/15/2011,16:14,Thursday,Home,51.06,126.9,80.5,84.9,9.08,38.1,36.1,No,fast,No
19,12/15/2011,07:19,Thursday,GSK,51.68,123.5,68.1,75.8,9.08,45.6,40.9,No,slow,No
20,12/14/2011,16:20,Wednesday,Home,51.04,123.4,75.1,79.4,9.08,40.8,38.6,No,fast,No
21,12/14/2011,07:23,Wednesday,GSK,51.67,123.5,76.6,82.7,9.08,40.5,37.5,No,fast,No
22,12/13/2011,17:43,Tuesday,Home,51.15,130.6,74.8,82.4,9.08,41.0,37.2,No,slow,No
23,12/13/2011,07:25,Tuesday,GSK,49.19,126.1,65.4,74.2,9.08,45.1,39.8,No,slow,No
24,12/12/2011,07:20,Monday,GSK,49.02,126.1,65.7,74.0,9.76,44.8,39.7,No,slow,No
25,12/9/2011,12:04,Friday,Home,51.14,126.8,87.3,90.2,9.76,35.2,34.0,No,fast,No
26,12/9/2011,07:22,Friday,GSK,51.69,128.4,74.0,77.3,9.76,41.9,40.1,No,slow,No
27,12/8/2011,17:41,Thursday,Home,51.07,125.0,74.6,81.5,9.76,41.1,37.6,No,slow,No
28,12/8/2011,07:14,Thursday,GSK,51.63,134.4,76.5,84.3,9.76,40.5,36.7,No,fast,No
29,12/7/2011,16:12,Wednesday,Home,51.10,126.5,79.9,85.6,9.76,38.4,35.8,No,fast,No
30,12/7/2011,07:18,Wednesday,GSK,51.64,124.6,73.6,82.0,9.76,42.1,37.8,No,slow,No
31,12/6/2011,17:24,Tuesday,Home,51.25,123.5,77.3,81.9,9.16,39.8,37.6,No,fast,No
32,12/6/2011,07:24,Tuesday,GSK,51.64,122.3,69.3,74.7,9.16,44.7,41.5,No,slow,No
33,12/5/2011,16:18,Monday,Home,50.18,124.0,71.0,79.5,9.16,42.4,37.9,No,slow,No
42,11/24/2011,16:15,Thursday,Home,51.49,126.6,74.0,82.8,9.3,41.8,37.3,No,slow,No
43,11/24/2011,07:23,Thursday,GSK,51.69,124.9,73.3,80.3,9.3,42.3,38.6,No,slow,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,8/9/2011,17:13,Tuesday,Home,51.15,127.1,72.1,82.3,8.54,42.5,37.3,No,slow,No
172,8/9/2011,08:15,Tuesday,GSK,49.08,134.8,60.5,67.2,8.54,48.7,43.8,No,slow,No
173,8/8/2011,17:05,Monday,Home,52.35,127.5,76.9,84.2,8.54,40.9,37.3,No,fast,No
174,8/8/2011,08:07,Monday,GSK,49.25,126.3,68.5,78.2,8.54,43.1,37.8,No,slow,No
175,8/5/2011,17:00,Friday,Home,51.94,126.7,74.5,82.6,8.48,41.9,37.7,No,slow,No
176,8/5/2011,08:20,Friday,GSK,49.13,123.9,74.1,79.9,8.48,39.8,36.9,No,slow,No
177,8/4/2011,17:38,Thursday,Home,50.96,131.9,70.3,78.5,8.48,43.5,38.9,No,slow,No
178,8/4/2011,08:17,Thursday,GSK,49.12,122.4,71.5,77.3,8.48,41.2,38.2,No,slow,No
179,8/3/2011,17:14,Wednesday,Home,51.64,125.0,72.2,78.7,8.48,42.9,39.4,No,slow,No
180,8/3/2011,08:06,Wednesday,GSK,49.06,121.9,71.5,78.7,8.48,41.2,37.4,No,slow,No
181,8/2/2011,17:22,Tuesday,Home,51.16,124.2,76.3,83.2,8.48,40.2,36.9,No,fast,No
182,8/2/2011,07:38,Tuesday,GSK,53.48,124.9,68.8,78.8,8.48,46.7,40.7,No,slow,No
184,7/29/2011,08:22,Friday,GSK,49.07,121.1,73.2,77.7,8.45,40.2,37.9,No,slow,No
185,7/28/2011,17:46,Thursday,Home,51.09,128.5,76.0,84.8,8.45,40.3,36.2,No,fast,No
186,7/28/2011,08:11,Thursday,GSK,49.11,120.1,69.1,73.1,8.45,42.6,40.3,No,slow,No
187,7/27/2011,17:24,Wednesday,Home,50.98,124.9,68.3,71.9,8.45,44.8,42.6,No,slow,No
188,7/27/2011,08:15,Wednesday,GSK,48.82,124.5,70.4,77.8,8.45,41.6,37.6,No,slow,No
189,7/26/2011,17:15,Tuesday,Home,51.28,122.1,43.7,51.5,8.45,70.5,59.8,No,slow,No
190,7/26/2011,08:11,Tuesday,GSK,49.16,122.6,71.9,76.8,8.45,41.0,38.4,No,slow,No
191,7/25/2011,16:59,Monday,Home,51.05,126.6,70.4,78.8,8.45,51.1,38.9,No,slow,No
192,7/25/2011,08:06,Monday,GSK,48.32,121.2,63.4,78.4,8.45,45.7,37.0,No,slow,No
193,7/22/2011,16:47,Friday,Home,51.24,126.3,75.8,81.8,8.28,40.6,37.6,No,fast,No
194,7/22/2011,08:28,Friday,GSK,51.05,123.3,88.9,96.7,8.28,34.5,31.7,Yes,fast,No
195,7/21/2011,07:59,Thursday,GSK,48.35,129.3,81.5,89.0,8.28,35.6,32.6,Yes,fast,No
196,7/20/2011,17:17,Wednesday,Home,53.47,124.0,58.6,71.0,7.89,54.8,45.2,No,slow,No
197,7/20/2011,08:24,Wednesday,GSK,48.50,125.8,75.7,87.3,7.89,38.5,33.3,Yes,fast,No
198,7/19/2011,17:17,Tuesday,Home,51.16,126.7,92.2,102.6,7.89,33.3,29.9,Yes,fast,No
199,7/19/2011,08:11,Tuesday,GSK,50.96,124.3,82.3,96.4,7.89,37.2,31.7,Yes,fast,No
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No,slow,No
201,7/14/2011,08:03,Thursday,GSK,50.90,123.7,76.2,95.1,7.89,40.1,32.1,Yes,fast,No

In [78]:
#replacing values with new value
travel_df_no_missing.loc[travel_df_no_missing['FuelEconomy']== '-', 'FuelEconomy']=0

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [79]:
travel_df_no_missing.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed,Police,new_FuelEconomy
6,1/2/2012,17:31,Monday,Home,51.37,123.2,82.9,87.3,0,37.2,35.3,No,fast,No,0.0
7,1/2/2012,07:34,Monday,GSK,49.01,128.3,77.5,85.9,0,37.9,34.3,No,fast,No,0.0
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No,fast,No,NaN
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No,slow,No,NaN
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No,slow,No,NaN

In [83]:
travel_df_no_missing['FuelEconomy'] = travel_df_no_missing['FuelEconomy'].astype(float)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [84]:
#Interquartile Range Method

q1 = travel_df_no_missing['FuelEconomy'].quantile(.25)
q3 = travel_df_no_missing['FuelEconomy'].quantile(.75)
iqr = q3-q1
toprange = q3 + iqr * 1.5
botrange = q1 - iqr * 1.5

newdf = travel_df_no_missing.copy()
newdf = newdf.drop(newdf[newdf['FuelEconomy'] > toprange].index)
newdf = newdf.drop(newdf[newdf['FuelEconomy'] < botrange].index)

newdf.head()
newdf.head()

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Speed,Police,new_FuelEconomy
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No,fast,No,NaN
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No,slow,No,NaN
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No,slow,No,NaN
11,12/21/2011,07:45,Wednesday,GSK,51.77,124.8,71.7,78.9,8.89,43.3,39.4,No,slow,No,NaN
12,12/20/2011,16:05,Tuesday,Home,51.45,130.1,75.2,82.7,8.89,41.1,37.3,No,fast,No,NaN